
export type Skill = {
    id: string;
    name: string;
    classification: "Магия" | "Раса" | "Общий";
    timing: string;
    check?: string;
    target: string;
    range: string;
    cost: string; // Keep as string for "1 MP" or "-"
    effect: string;
    description: string;
    requirements: {
        gl: number;
        race?: "Человек" | "Эльф" | "Ангел" | "Зверолюд";
        style?: "Энчантер" | "Кастер" | "Шутер" | "Шейпшифтер" | "Сейкрифер" | "Мистик";
        making?: boolean; // Can be obtained at making
        skills?: string[];
    };
    critical?: string;
};

export const SKILLS: Skill[] = [
    // --- Расовые Навыки ---
    {
        id: "human_racial",
        name: "Расовый Навык: Человек",
        classification: "Раса",
        timing: "Пассив",
        target: "Сам",
        range: "-",
        cost: "-",
        effect: "Только для Людей. Ваш WP +1.",
        description: "Навык, отражающий талант людей обладать силой. Адаптивность к среде и несгибаемый дух.",
        requirements: { gl: 0, race: "Человек", making: true }
    },
    {
        id: "elf_racial",
        name: "Расовый Навык: Эльф",
        classification: "Раса",
        timing: "Сразу после проверки меткости",
        check: "Автоматический успех",
        target: "Сам",
        range: "-",
        cost: "-",
        effect: "Только для Эльфов. +3 к значению достижения проверки меткости с использованием Магического Значения. 1 раз за Сценарий.",
        description: "Навык, отражающий тонкий и мощный магический талант эльфов.",
        requirements: { gl: 0, race: "Эльф", making: true }
    },
    {
        id: "angel_racial",
        name: "Расовый Навык: Ангел",
        classification: "Раса",
        timing: "Перед Дайс-роллом",
        check: "Автоматический успех",
        target: "Одиночная",
        range: "В упор",
        cost: "-",
        effect: "Только для Ангелов. +2D к HP, восстанавливаемому лечебной магией. 1 раз за Сценарий.",
        description: "Навык, усиливающий целительную силу благодаря возвышенному духу и милосердному сердцу ангела.",
        requirements: { gl: 0, race: "Ангел", making: true }
    },
    {
        id: "therian_racial",
        name: "Расовый Навык: Зверолюд",
        classification: "Раса",
        timing: "Сразу после проверки меткости",
        check: "Автоматический успех",
        target: "Сам",
        range: "-",
        cost: "-",
        effect: "Только для Зверолюдей. Если вы были атакованы, ваше Уклонение +3. Этот эффект длится до конца Основного процесса (Main Process). 1 раз за Сценарий.",
        description: "Навык, отражающий способность зверолюдей, обладающих превосходными чувствами и ловкостью, избегать опасности инстинктивной реакцией.",
        requirements: { gl: 0, race: "Зверолюд", making: true }
    },

    // --- Общие Навыки (General Skills) ---
    {
        id: "mana_inflow",
        name: "Mana Inflow (Приток маны)",
        classification: "Магия",
        timing: "Пассив / Меджер",
        check: "Магическая проверка",
        target: "Сам",
        range: "-",
        cost: "0 MP",
        effect: "Можно использовать магию. Можно выполнять магические проверки, подтверждающие наличие таланта к магии.",
        description: "Магия, делающая первый шаг в качестве мага. Важный навык, используемый при экзамене на становление учеником мага в Первом сценарии.",
        requirements: { gl: 0, making: true }
    },
    {
        id: "housework",
        name: "Housework (Работа по дому)",
        classification: "Общий",
        timing: "Пассив",
        target: "Сам",
        range: "-",
        cost: "-",
        effect: "+GL к различным проверкам, касающимся работы по дому. Способность для проверки назначает ГМ.",
        description: "Навык, отражающий умение в деятельности по поддержанию повседневной жизни. Полезен в сценариях «медленной жизни» (повседневности).",
        requirements: { gl: 0 }
    },
    {
        id: "craft",
        name: "Craft (Ремесло)",
        classification: "Общий",
        timing: "Пассив",
        target: "Сам",
        range: "-",
        cost: "-",
        effect: "+GL к проверкам, касающимся создания вещей: изготовление предметов, ремонт, обработка. Способность для проверки назначает ГМ.",
        description: "Техника владения инструментами и материалами, создания и починки повседневных вещей. Полезен в сценариях «медленной жизни».",
        requirements: { gl: 0 }
    },
    {
        id: "colorless_shot",
        name: "Colorless Shot (Бесцветный выстрел)",
        classification: "Магия",
        timing: "Меджер",
        check: "Магич. Знач.",
        target: "Одиночная",
        range: "Ближняя",
        cost: "1 MP",
        effect: "Наносит урон без атрибута. Урон +[1D+3]. Атрибут урона — <Нет>.",
        description: "Учебная магическая атака, просто швыряющая чистую магическую силу.",
        requirements: { gl: 1 },
        critical: "Увеличение дайс-ролла"
    },
    {
        id: "singing",
        name: "Singing (Пение)",
        classification: "Магия",
        timing: "Пассив",
        target: "Сам",
        range: "-",
        cost: "-",
        effect: "Магическое Значение +1.",
        description: "Навык, делающий голос плавным. Вы начинаете лучше петь, улучшается дикция. Изучение вокала делает магическое песнопение более эффективным.",
        requirements: { gl: 1 }
    },
    {
        id: "coding",
        name: "Coding (Кодирование)",
        classification: "Магия",
        timing: "Пассив",
        target: "Сам",
        range: "-",
        cost: "-",
        effect: "Снижает расход MP на магию на -1 (не может стать ниже 0).",
        description: "Изучение стихосложения и грамматики для повышения эффективности песнопений и снижения расхода маны.",
        requirements: { gl: 1 }
    },
    {
        id: "tactics",
        name: "Tactics (Тактика)",
        classification: "Магия",
        timing: "Сетап",
        check: "【Знание】",
        target: "Одиночная",
        range: "Ближняя",
        cost: "7 MP",
        effect: "При получении выберите любой Плохой Статус (кроме Окаменения). Проведите Противостояние с целью по 【Знанию】. При победе накладывает выбранный статус.",
        description: "Не проводит магического воздействия, ограничивает действия цели (тактически).",
        requirements: { gl: 1 }
    },
    {
        id: "negotiation",
        name: "Negotiation (Переговоры)",
        classification: "Общий",
        timing: "Пассив",
        target: "Сам",
        range: "-",
        cost: "-",
        effect: "+GL к различным проверкам, касающимся переговоров. Способность для проверки назначает ГМ.",
        description: "Навык, позволяющий привести переговоры к желаемому результату. Полезен в сценариях «медленной жизни».",
        requirements: { gl: 1 }
    },
    {
        id: "search",
        name: "Search (Поиск)",
        classification: "Общий",
        timing: "Пассив",
        target: "Сам",
        range: "-",
        cost: "-",
        effect: "+GL к проверкам, касающимся поиска.",
        description: "Техника для обнаружения скрытых проходов, сундуков с сокровищами, опасных ловушек и т.д.",
        requirements: { gl: 1 }
    },
    {
        id: "sneak",
        name: "Sneak (Скрытность)",
        classification: "Общий",
        timing: "Пассив",
        target: "Сам",
        range: "-",
        cost: "-",
        effect: "+GL к проверкам скрытности, прятанья, выслеживания, преследования.",
        description: "Техника для достижения цели незамеченным, обманывая зрение и слух врага.",
        requirements: { gl: 1 }
    },
    {
        id: "intercept",
        name: "Intercept (Перехват)",
        classification: "Общий",
        timing: "Сразу после проверки меткости",
        check: "Магич. Знач.",
        target: "Сам",
        range: "-",
        cost: "6 MP",
        effect: "Сразу после проверки меткости атаки, полученной вами, выполните проверку Магического Значения со сложностью, равной значению достижения атаки. При успехе атака считается промахнувшейся. 1 раз за Сценарий.",
        description: "Навык, позволяющий контратаковать атаку противника магией и нейтрализовать её.",
        requirements: { gl: 2 }
    },
    {
        id: "confusion",
        name: "Confusion (Замешательство)",
        classification: "Общий",
        timing: "Сетап",
        check: "【Знание】",
        target: "Одиночная",
        range: "Ближняя",
        cost: "2 MP",
        effect: "Эффективно, если у цели есть Лим-Энеми (свита). Проведите Противостояние с целью по 【Знанию】. При победе Уклонение цели -3. Этот эффект длится до конца раунда.",
        description: "Техника нарушения координации Коренного врага и свиты для получения тактического преимущества.",
        requirements: { gl: 2 }
    },
    {
        id: "survival",
        name: "Survival (Выживание)",
        classification: "Общий",
        timing: "Пассив",
        target: "Сам",
        range: "-",
        cost: "-",
        effect: "+2 к различным проверкам, касающимся активности на природе (аутдор). Способность для проверки назначает ГМ.",
        description: "Навык, отражающий действия при проверках выживания в дикой природе или при бедствиях.",
        requirements: { gl: 3, skills: ["housework"] }
    },
    {
        id: "teleport",
        name: "Teleport (Телепорт)",
        classification: "Магия",
        timing: "Майнер",
        check: "Автоматический успех",
        target: "Сам",
        range: "-",
        cost: "10 MP",
        effect: "Становится возможным перемещение на 2 шага дистанции. Также можно перемещаться, игнорируя состояния Зацеп, Скольжение, Блокада.",
        description: "Магия перемещения на короткие дистанции. Помешать перемещению невозможно.",
        requirements: { gl: 4 }
    },
    {
        id: "silent_spell",
        name: "Silent Spell (Тихое заклинание)",
        classification: "Магия",
        timing: "Пассив",
        target: "Сам",
        range: "-",
        cost: "-",
        effect: "Магическое Значение +3. Дополнительно +1D к дайсам проверки.",
        description: "Навык выполнения песнопения без голоса благодаря высокоуровневому анализу магии.",
        requirements: { gl: 6, skills: ["singing", "coding"] }
    },

    // --- Энчантер (Enchanter) ---
    {
        id: "enchant_weapon",
        name: "Enchant Weapon (Зачарование оружия)",
        classification: "Магия",
        timing: "Меджер",
        check: "Магич. Знач.",
        target: "Одиночная",
        range: "Оружие",
        cost: "1 MP",
        effect: "Выполните атаку, используя оружие, назначенное Фокусным инструментом. К урону +2D. Также применяется поправка на меткость и урон оружия.",
        description: "Базовый навык Энчантера, придающий обычной атаке магический эффект путем вложения маны в оружие.",
        requirements: { gl: 0, style: "Энчантер", making: true },
        critical: "Увеличение дайс-ролла"
    },
    {
        id: "impact_break",
        name: "Impact Break (Ударный разрыв)",
        classification: "Магия",
        timing: "Перед Броском Урона",
        check: "Автоматический успех",
        target: "Сам",
        range: "-",
        cost: "3 MP",
        effect: "Урон +10. Этот эффект длится до конца Основного процесса.",
        description: "Навык, повышающий мощь удара путем мгновенной подачи маны в оружие в момент атаки.",
        requirements: { gl: 0, style: "Энчантер" }
    },
    {
        id: "magic_parry",
        name: "Magic Parry (Магическое парирование)",
        classification: "Магия",
        timing: "Сразу после Броском Урона",
        check: "Автоматический успех",
        target: "Сам",
        range: "-",
        cost: "3 MP",
        effect: "Получаемый вами урон уменьшается на -[(GL) D + 4].",
        description: "Навык, позволяющий принять атаку врага на оружие, усиленное магией.",
        requirements: { gl: 0, style: "Энчантер" }
    },
    {
        id: "fake_attack",
        name: "Fake Attack (Ложная атака)",
        classification: "Магия",
        timing: "Сетап",
        check: "【Ловкость】",
        target: "Одиночная",
        range: "В упор",
        cost: "3 MP",
        effect: "Проведите Противостояние с целью по 【Ловкости】. При победе накладывает Стан.",
        description: "Навык, заставляющий цель застыть, имитируя серию скоростных ударов.",
        requirements: { gl: 1, style: "Энчантер" }
    },
    {
        id: "weapon_tornado",
        name: "Weapon Tornado (Торнадо оружия)",
        classification: "Магия",
        timing: "Майнер",
        check: "Автоматический успех",
        target: "Сам",
        range: "-",
        cost: "1 MP",
        effect: "Магическое Значение +3. Этот эффект длится до конца Основного процесса.",
        description: "Усиление физических способностей магией. Увеличивает количество ударов, нанося шквал атак подобно буре.",
        requirements: { gl: 1, style: "Энчантер" }
    },
    {
        id: "quick_movement",
        name: "Quick Movement (Быстрое движение)",
        classification: "Магия",
        timing: "Сетап",
        check: "【Ловкость】",
        target: "Одиночная",
        range: "В упор",
        cost: "4 MP",
        effect: "Проведите Противостояние с целью по 【Ловкости】. При победе вы можете действовать раньше цели.",
        description: "Навык для захвата инициативы в начале боя.",
        requirements: { gl: 1, style: "Энчантер" }
    },
    {
        id: "life_enchant",
        name: "Life Enchant (Зачарование жизни)",
        classification: "Магия",
        timing: "Сетап / Майнер",
        check: "Магическая проверка",
        target: "Сам",
        range: "-",
        cost: "1 MP",
        effect: "Восстанавливает HP на [2D + (GL × 2)].",
        description: "Навык выживания, делающий возможным самолечение.",
        requirements: { gl: 1, style: "Энчантер" },
        critical: "Увеличение дайс-ролла"
    },
    // ... Additional Enchanter skills can be added similarly

    // --- Кастер (Caster) ---
    {
        id: "full_burst",
        name: "Full Burst (Полный залп)",
        classification: "Магия",
        timing: "Меджер",
        check: "Магич. Знач.",
        target: "Одиночная",
        range: "Ближняя",
        cost: "1 MP",
        effect: "Выполняет атаку, высвобождая магическую силу в цель. Урон + [2D+2].",
        description: "Базовая атакующая магия Кастера.",
        requirements: { gl: 0, style: "Кастер", making: true },
        critical: "Увеличение дайс-ролла"
    },
    {
        id: "magic_shield",
        name: "Magic Shield (Магический щит)",
        classification: "Магия",
        timing: "Сразу после Броска Урона",
        check: "Автоматический успех",
        target: "Сам",
        range: "-",
        cost: "3 MP",
        effect: "Уменьшает получаемый вами урон на -[(GL) D + 5].",
        description: "Навык для защиты себя от вражеских атак.",
        requirements: { gl: 0, style: "Кастер" }
    },
    {
        id: "crush_bullet",
        name: "Crush Bullet (Разрушительная пуля)",
        classification: "Магия",
        timing: "Перед Броском Урона",
        check: "Автоматический успех",
        target: "Сам",
        range: "-",
        cost: "4 MP",
        effect: "Урон +12. Этот эффект длится до конца Основного процесса.",
        description: "Навык, увеличивающий ударную силу магической атаки.",
        requirements: { gl: 0, style: "Кастер" }
    },
    {
        id: "mirage_magic",
        name: "Mirage Magic (Магия миража)",
        classification: "Магия",
        timing: "Сетап",
        check: "【Знание】",
        target: "Одиночная",
        range: "Ближняя",
        cost: "3 MP",
        effect: "Проведите Противостояние с целью по 【Знанию】. При победе накладывает Стан.",
        description: "Отнимает у противника способность реагировать на изменение ситуации, нанося удар по сознанию созданной иллюзией.",
        requirements: { gl: 1, style: "Кастер" }
    },
    {
        id: "arc_blast",
        name: "Arc Blast (Дуга взрыва)",
        classification: "Магия",
        timing: "Майнер",
        check: "Автоматический успех",
        target: "Сам",
        range: "-",
        cost: "4 MP",
        effect: "Целью атаки становится Область. Этот эффект длится до конца Основного процесса.",
        description: "Атакующая магия по площади, эффективная против множества врагов.",
        requirements: { gl: 1, style: "Кастер" }
    },
    {
        id: "accel_spell",
        name: "Accel Spell (Ускоряющее заклинание)",
        classification: "Магия",
        timing: "Сетап",
        check: "【Знание】",
        target: "Одиночная",
        range: "Ближняя",
        cost: "4 MP",
        effect: "Проведите Противостояние с целью по 【Знанию】. При победе вы можете действовать раньше цели в этом раунде.",
        description: "Магия для захвата инициативы.",
        requirements: { gl: 1, style: "Кастер" }
    },
    {
        id: "life_song",
        name: "Life Song (Песнь жизни)",
        classification: "Магия",
        timing: "Сетап / Майнер",
        check: "Магическая проверка",
        target: "Сам",
        range: "-",
        cost: "1 MP",
        effect: "Восстанавливает HP на [2D + GL].",
        description: "Магия, исцеляющая раны, накладывая силу жизни на «распев» (спелл).",
        requirements: { gl: 1, style: "Кастер" },
        critical: "Увеличение дайс-ролла"
    },

    // --- Шутер (Shooter) ---
    {
        id: "magic_arrow",
        name: "Magic Arrow (Магическая стрела)",
        classification: "Магия",
        timing: "Меджер",
        check: "Магич. Знач.",
        target: "Одиночная",
        range: "Средняя",
        cost: "1 MP",
        effect: "Выполняет дальнобойную высокоточную атакующую магию по цели. Магическое Значение +2. Урон + [1D+4].",
        description: "Базовая магия Шутера.",
        requirements: { gl: 0, style: "Шутер", making: true },
        critical: "Увеличение дайс-ролла"
    },
    {
        id: "charge_bullet",
        name: "Charge Bullet (Заряженная пуля)",
        classification: "Магия",
        timing: "Перед Броском Урона",
        check: "Автоматический успех",
        target: "Сам",
        range: "-",
        cost: "3 MP",
        effect: "Урон +10. Этот эффект длится до конца Основного процесса.",
        description: "Навык, усиливающий ману и повышающий урон.",
        requirements: { gl: 0, style: "Шутер" }
    },
    {
        id: "sniping",
        name: "Sniping (Снайпинг)",
        classification: "Магия",
        timing: "Сразу после проверки меткости",
        check: "Автоматический успех",
        target: "Сам",
        range: "-",
        cost: "5 MP",
        effect: "Вы можете изменить результат одного из дайсов, брошенных при проверке меткости, на 6.",
        description: "Навык, присущий только Шутеру — не сводить глаз с поведения врага до момента выпуска магической атаки.",
        requirements: { gl: 0, style: "Шутер" }
    },
    {
        id: "hit_and_run",
        name: "Hit and Run (Удар и отход)",
        classification: "Магия",
        timing: "Сетап",
        check: "Автоматический успех",
        target: "Сам",
        range: "-",
        cost: "2 MP",
        effect: "Уклонение +3. Этот эффект длится до конца раунда.",
        description: "Навык, ставший базовой тактикой Шутера: сохранять определенную дистанцию с врагом.",
        requirements: { gl: 1, style: "Шутер" }
    },
    {
        id: "multi_lockon",
        name: "Multi Lock-on (Мульти-захват)",
        classification: "Магия",
        timing: "Майнер",
        check: "Автоматический успех",
        target: "Сам",
        range: "-",
        cost: "4 MP",
        effect: "Целью атаки становится Область. Этот эффект длится до конца Основного процесса.",
        description: "Магия атаки по площади, эффективная против множества врагов.",
        requirements: { gl: 1, style: "Шутер" }
    },
    {
        id: "phantom_wave",
        name: "Phantom Wave (Фантомная волна)",
        classification: "Магия",
        timing: "Сетап",
        check: "【Знание】",
        target: "Одиночная",
        range: "Средняя",
        cost: "3 MP",
        effect: "Проведите Противостояние с целью по 【Знанию】. При победе накладывает Стан.",
        description: "Навык, наносящий сильный ментальный стресс мозгу противника и отнимающий концентрацию.",
        requirements: { gl: 1, style: "Шутер" }
    },
    {
        id: "healing_shot",
        name: "Healing Shot (Исцеляющий выстрел)",
        classification: "Магия",
        timing: "Сетап / Майнер",
        check: "Магическая проверка",
        target: "Одиночная",
        range: "Средняя",
        cost: "1 MP",
        effect: "Восстанавливает HP цели на 2D.",
        description: "Исцеляющая магия, которую можно применять не только на себя, но и на других.",
        requirements: { gl: 1, style: "Шутер" },
        critical: "Увеличение дайс-ролла"
    },

    // --- Шейпшифтер (Shapeshifter) ---
    {
        id: "fargin",
        name: "Fargin (Фарджин)",
        classification: "Магия",
        timing: "Меджер",
        check: "Магич. Знач.",
        target: "Сам",
        range: "Оружие",
        cost: "1 MP",
        effect: "Атака с использованием рукопашного оружия. Урон +2D. Также применяется поправка на меткость и урон оружия.",
        description: "Магия, превращающая собственное тело в оружие.",
        requirements: { gl: 0, style: "Шейпшифтер", making: true },
        critical: "Увеличение дайс-ролла"
    },
    {
        id: "soul_fist",
        name: "Soul Fist (Кулак души)",
        classification: "Магия",
        timing: "Перед Броском Урона",
        check: "Автоматический успех",
        target: "Сам",
        range: "-",
        cost: "6 MP",
        effect: "Урон атаки +8. Атака становится Проникающей (игнорирует броню).",
        description: "Магия для повышения мощи кулака. Навык, вливающий ману в кулак и пробивающий броню врага насквозь.",
        requirements: { gl: 0, style: "Шейпшифтер" }
    },
    {
        id: "life_harmony",
        name: "Life Harmony (Гармония жизни)",
        classification: "Магия",
        timing: "Сетап / Майнер",
        check: "Магическая проверка",
        target: "Сам",
        range: "-",
        cost: "1 MP",
        effect: "Восстанавливает HP на [2D + 5].",
        description: "Исцеляющая магия самолечения, усиливающая жизненную силу за счет повышения единства с природой.",
        requirements: { gl: 0, style: "Шейпшифтер" },
        critical: "Увеличение дайс-ролла"
    },
    {
        id: "flicker_arm",
        name: "Flicker Arm (Мерцающая рука)",
        classification: "Магия",
        timing: "Майнер",
        check: "Автоматический успех",
        target: "Сам",
        range: "-",
        cost: "3 MP",
        effect: "Увеличивает категорию дальности атаки на 1 шаг. Этот эффект длится до конца Основного процесса.",
        description: "Магия трансформации, позволяющая атаке достичь даже удаленных врагов, гибко удлиняя руку.",
        requirements: { gl: 1, style: "Шейпшифтер" }
    },
    {
        id: "butterfly_float",
        name: "Butterfly Float (Парение бабочки)",
        classification: "Магия",
        timing: "Сетап",
        check: "Автоматический успех",
        target: "Сам",
        range: "-",
        cost: "4 MP",
        effect: "Магическое Значение +2, Уклонение +2. Этот эффект длится до конца раунда.",
        description: "Навык, трансформирующий тело для порхания, подобно бабочке, и увеличивающий мобильность.",
        requirements: { gl: 1, style: "Шейпшифтер" }
    },
    {
        id: "fantasista",
        name: "Fantasista (Фантазиста)",
        classification: "Магия",
        timing: "Сетап",
        check: "【Ловкость】",
        target: "Одиночная",
        range: "Средняя",
        cost: "4 MP",
        effect: "Проведите Противостояние с целью по 【Ловкости】. При победе накладывает Панику.",
        description: "Навык, сбивающий прицел противника финтами и неуловимой работой ног.",
        requirements: { gl: 1, style: "Шейпшифтер" }
    },
    {
        id: "shed_skin",
        name: "Shed Skin (Линька)",
        classification: "Магия",
        timing: "Сразу после Броска Урона",
        check: "Автоматический успех",
        target: "Сам",
        range: "-",
        cost: "3 MP",
        effect: "Уменьшает получаемый вами урон на -[(GL+1) D].",
        description: "Защитная магия трансформации, позволяющая сбросить кожу и защитить себя от атаки врага.",
        requirements: { gl: 1, style: "Шейпшифтер" }
    },

    // --- Сейкрифер (Sacrifier) ---
    {
        id: "invoke",
        name: "Invoke (Мольба)",
        classification: "Магия",
        timing: "Меджер",
        check: "Магич. Знач.",
        target: "Одиночная",
        range: "Ближняя",
        cost: "1 MP",
        effect: "Выполняет атаку святой магической силой по цели. Урон + [1D+4].",
        description: "Базовая магия Сейкрифера.",
        requirements: { gl: 0, style: "Сейкрифер", making: true },
        critical: "Увеличение дайс-ролла"
    },
    {
        id: "holy_break",
        name: "Holy Break (Святой разлом)",
        classification: "Магия",
        timing: "Перед Броском Урона",
        check: "Автоматический успех",
        target: "Одиночная",
        range: "Ближняя",
        cost: "4 MP",
        effect: "Урон +10.",
        description: "Навык, дарующий божественную защиту и повышающий силу в бою.",
        requirements: { gl: 0, style: "Сейкрифер" }
    },
    {
        id: "holy_light",
        name: "Holy Light (Святой свет)",
        classification: "Магия",
        timing: "Сетап / Майнер",
        check: "Автоматический успех",
        target: "Одиночная",
        range: "Ближняя",
        cost: "1 MP",
        effect: "Магическое Значение цели +GL. Этот эффект длится до конца раунда.",
        description: "Магия, в которой свет, несущий божественную благодать, направляет атаку к успеху.",
        requirements: { gl: 0, style: "Сейкрифер" }
    },
    {
        id: "heavenly_step",
        name: "Heavenly Step (Небесный шаг)",
        classification: "Магия",
        timing: "Сетап / Майнер",
        check: "Автоматический успех",
        target: "Одиночная",
        range: "Ближняя",
        cost: "1 MP",
        effect: "Уклонение цели +GL. Этот эффект длится до конца раунда.",
        description: "Навык, дарующий защиту (благословение) для уклонения от вражеских атак.",
        requirements: { gl: 1, style: "Сейкрифер" }
    },
    {
        id: "divine_will",
        name: "Divine Will (Божественная воля)",
        classification: "Магия",
        timing: "Сетап",
        check: "【Любовь】",
        target: "Одиночная",
        range: "Ближняя",
        cost: "3 MP",
        effect: "Проведите Противостояние с целью по 【Любви】. При победе накладывает Стан.",
        description: "Навык, подавляющий и устрашающий цель величием бога.",
        requirements: { gl: 1, style: "Сейкрифер" }
    },
    {
        id: "heal",
        name: "Heal (Исцеление)",
        classification: "Магия",
        timing: "Сетап / Майнер",
        check: "Магическая проверка",
        target: "Одиночная",
        range: "Ближняя",
        cost: "1 MP",
        effect: "Восстанавливает HP цели на [2D + (GL × 4)].",
        description: "Исцеляющая магия, залечивающая раны и позволяющая продолжать бой.",
        requirements: { gl: 1, style: "Сейкрифер" },
        critical: "Увеличение дайс-ролла"
    },
    {
        id: "divine_shield",
        name: "Divine Shield (Божественный щит)",
        classification: "Магия",
        timing: "Сразу после Броска Урона",
        check: "Автоматический успех",
        target: "Одиночная",
        range: "Ближняя",
        cost: "2 MP",
        effect: "Уменьшает получаемый целью урон на -[3D + 3].",
        description: "Оборонительная магия, защищающая тело святой силой.",
        requirements: { gl: 1, style: "Сейкрифер" }
    },

    // --- Мистик (Mystic) ---
    {
        id: "spirit_connect",
        name: "Spirit Connect (Духовная связь)",
        classification: "Магия",
        timing: "Меджер",
        check: "Магич. Знач.",
        target: "Одиночная",
        range: "Ближняя",
        cost: "1 MP",
        effect: "Повышает священную магическую силу и выполняет атаку. Урон + [2D+2].",
        description: "Магия, являющаяся основой Мистика.",
        requirements: { gl: 0, style: "Мистик", making: true },
        critical: "Увеличение дайс-ролла"
    },
    {
        id: "holy_arm",
        name: "Holy Arm (Святая рука)",
        classification: "Магия",
        timing: "Пассив",
        target: "Сам",
        range: "-",
        cost: "-",
        effect: "Магическое Значение +2, урон от атаки +7.",
        description: "Навык, постоянно вмещающий божественную защиту.",
        requirements: { gl: 0, style: "Мистик" }
    },
    {
        id: "god_speed",
        name: "God Speed (Божественная скорость)",
        classification: "Магия",
        timing: "Сетап",
        check: "【Мистика】",
        target: "Сам",
        range: "-",
        cost: "5 MP",
        effect: "Проведите Противостояние с целью по 【Мистике】. При победе вы можете действовать раньше цели в этом раунде.",
        description: "Божественный голос подгоняет душу и ускоряет действия.",
        requirements: { gl: 0, style: "Мистик" }
    },
    {
        id: "shift_resonance",
        name: "Shift Resonance (Сдвиг резонанса)",
        classification: "Магия",
        timing: "Сразу после Броска Урона",
        check: "Автоматический успех",
        target: "Сам",
        range: "-",
        cost: "2 MP",
        effect: "Уменьшает получаемый вами урон на -[GL + 1] D.",
        description: "Таинственная защитная магия, уменьшающая урон от врага путем поселения божественности в «собственном существовании».",
        requirements: { gl: 1, style: "Мистик" }
    },
    {
        id: "holy_spirit",
        name: "Holy Spirit (Святой дух)",
        classification: "Магия",
        timing: "Сетап",
        check: "【Мистика】",
        target: "Одиночная",
        range: "Ближняя",
        cost: "4 MP",
        effect: "Проведите Противостояние с целью по 【Мистике】. При победе накладывает Панику.",
        description: "Навык, демонстрирующий цели величие души бога и препятствующий инстинктивным действиям.",
        requirements: { gl: 1, style: "Мистик" }
    },
    {
        id: "pure_soul",
        name: "Pure Soul (Чистая душа)",
        classification: "Магия",
        timing: "Сетап / Майнер",
        check: "Магическая проверка",
        target: "Сам",
        range: "-",
        cost: "1 MP",
        effect: "Восстанавливает HP на [2D+5].",
        description: "Навык, восстанавливающий тело через исцеление души.",
        requirements: { gl: 1, style: "Мистик" },
        critical: "Увеличение дайс-ролла"
    },
    {
        id: "corruption_wave",
        name: "Corruption Wave (Волна искажения)",
        classification: "Магия",
        timing: "Майнер",
        check: "Автоматический успех",
        target: "Сам",
        range: "-",
        cost: "1 MP",
        effect: "Целью атаки становится Область. Также накладывает на цель Слип (Скольжение). Этот эффект длится до конца Основного процесса.",
        description: "Навык, расширяющий диапазон атаки духовной вибрацией и уничтожающий врагов.",
        requirements: { gl: 1, style: "Мистик" }
    }
];
